### PR TITLE
Update text orientation for all functional tests

### PR DESCRIPTION
**Pull request by stevenvergenz**
Rotate all the text 180 degrees to compensate for #124

### CODE REVIEW

**Comment by tombuMS** [comment]
I agree. If this is an issue specific to how unity handles the z direction, it should be fixed in our Unity code wouldn't you agree?

**Comment by stevenvergenz** [comment]
I agree, except I don't know how to! There's no transform field on text, and creating a new GameObject to rotate it adds a lot of complexity. Any preferred strategies for flipping it?

**Comment by eanders-MS** [comment]
Is it possible to reverse the UV's on the text texture?

**Comment by sorenhan** [comment]
As we talked about, we will hold off on this until we have a solution to flip the text in both TextMesh and TextMeshPro

**Pull request closed without merging**
